name = "editor-live-share"
main = "src/worker.js"
compatibility_date = "2024-05-29"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "RoomDurableObject" }
]



[vars]
# Comma-separated list of allowed origins for CORS and WS Origin checks
ALLOWED_ORIGINS = "http://127.0.0.1:8080,http://localhost:8080,https://editor.sanjaysingh.net"
# Optional: Cloudflare Turnstile secret; if empty, Turnstile is disabled
TURNSTILE_SECRET_KEY = ""
# Room TTL in seconds (default 3600 = 1 hour)
ROOM_TTL_SECONDS = "3600"
# Max viewers per room
MAX_VIEWERS = "50"
# Rate limit for room creation per IP per hour
CREATE_LIMIT_PER_HOUR = "20"

[observability]
enabled = true

[env.dev]
vars = { ALLOWED_ORIGINS = "http://127.0.0.1:8080,http://localhost:8080,https://editor.sanjaysingh.net" } 